name: snowflake_test
version: 1.0.0
config-version: 2
profile: snowflake_test
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  snowflake_test:
    +materialized: view
